apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mamad-azimi-jozani/argo-node-mysql.git
    targetRevision: HEAD 
    path: mychart
  destination:
    server: https://kubernetes.default.svc 
    namespace: argo-deploy                     
  syncPolicy:
    automated:
      prune: true                          
      selfHeal: true                      